apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault-secret-store

  target:
    name: backend-db-creds
    creationPolicy: Owner

  data:
  - secretKey: DB_HOST
    remoteRef:
      key: db-host
      
  - secretKey: DB_USER
    remoteRef:
      key: db-user

  - secretKey: DB_PASSWORD
    remoteRef:
      key: db-password

  - secretKey: DB_NAME
    remoteRef:
      key: db-name


