apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - vault-auth.yaml
  - secret-store.yaml
  - external-secret.yaml

namespace: prod
patches:
- path: depl-patch.yaml
