apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-external-secret
  namespace: postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault-secret-store

  target:
    name: cnpg-creds
    creationPolicy: Owner

  data:
  - secretKey: username
    remoteRef:
      key: username
      
  - secretKey: password
    remoteRef:
      key: password
