apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-secret-store
  namespace: postgres
spec:
  provider:
    azurekv:
      tenantId: "b3ac1073-f9f6-4753-af38-221f900fc3e9"
      vaultUrl: "https://vault-secret.vault.azure.net" 
      authSecretRef:
        clientId:
          name: azure-secret-sp
          key: ClientID
        clientSecret:
          name: azure-secret-sp
          key: ClientSecret
