apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      securityContext:
        runAsNonRoot: true
      initContainers:
      - name: wait-for-db
        image: postgres:15
        securityContext:
          runAsUser: 999  
        command:
          - sh
          - -c
          - |
            until pg_isready -h my-postgresql-rw.postgres.svc.cluster.local -p 5432; do
              echo "Waiting for PostgreSQL database to be ready..."
              sleep 5
            done
            echo "PostgreSQL database is up and running."
      containers:
      - name: backend
        image: prajapatirishi99/backend:bb9d3608315376a2836c781585703d74a9b7c54e
        ports:
          - containerPort: 8080
        envFrom:
          - secretRef:
              name: backend-db-creds
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false