apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert
  namespace: prod
spec:
  secretName: tls-cert
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - api.prajapatirishi.site
    - apiback.prajapatirishi.site
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-tls-cert
  namespace: argocd
spec:
  secretName: argo-tls-cert
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - argo.prajapatirishi.site


  