apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=prajapatirishi99/backend
    argocd-image-updater.argoproj.io/backend.force-update: "true"
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-secret
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  source:
    path: k8s-deploy/backend/overlays/prod
    repoURL: https://github.com/rishi-prajapati/PGP.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
