apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  source:
    path: k8s-deploy/frontend/overlays/prod
    repoURL: https://github.com/rishi-prajapati/PGP.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
