apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: frontend=prajapatirishi99/frontend
    argocd-image-updater.argoproj.io/frontend.force-update: "true"
    argocd-image-updater.argoproj.io/frontend.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-secret
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  source:
    path: k8s-deploy/frontend/overlays/prod
    repoURL: https://github.com/rishi-prajapati/PGP.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
